<?php

namespace AppBundle\Repository;

/**
 * Campo_afinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Campo_afinRepository extends \Doctrine\ORM\EntityRepository
{
}
