<?php

namespace AppBundle\Repository;

/**
 * Estado_solicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Estado_solicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
