<?php

namespace AppBundle\Repository;

/**
 * Solicitud_notaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Solicitud_notaRepository extends \Doctrine\ORM\EntityRepository
{
}
